# -*- coding: utf-8 -*-
"""prediccionVehiculoIdeal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12gGJZGqrfeEPU86pkToNfDMwLh7AQicv
"""

#Modulos
from sklearn import tree
import matplotlib.pyplot as np
clf = tree.DecisionTreeClassifier()

print ("Predice tu carro ideal")
print ("-----------------------")
print (" ")
print (" ")
print("Ingrese su salario promedio")
print("A    1.000.000 COP - 2.000.000 COP")
print("B    3.000.000 COP - 3.000.000 COP")
print("C    4.000.000 COP - 5.000.000 COP")
var1 = input("Salario ")

print("Escoge tipo de carroceria")
print("A   Sedan")
print("B   Cuope")
print("C   Suv")
var2 = input("Carroceria ")

print("Escoge el tipo de auto")
print ("A   Familiar")
print ("B   Soltero")
print ("C   Aventura")
var3 = input("Tipo Vehiculo ")

# Entrada de datos
inputs =[var1,var2, var3]
X= [[1,1,1],[1,2,2],[2,1,1],[3,1,1],[4,3,1]]
Y = ['Spark Gt', 'Chevrolet Sail', 'Chevrolet Beat','Mazda 2 Mod 2020','Mazda Cx-30 Prime Mt 2.0 4x2 2022']

# Indicatores
X= [[1,1,1],[1,2,2],[2,1,1],[3,1,1],[4,3,1]]
XPred = [[1,2,2],[2,1,1],[2,1,1],[4,3,1],[4,3,1]]

# Filtra los datos recolectados
clf = clf.fit(X, Y)

#Predice los datos
prediction = clf.predict([inputs])
print (" ")
print (" ")
print("---------------------------------------------------")
print("su vehiculo ideal con respecto a su presupuesto es:")
print (" ")
print(prediction)
print (" ")
print (" ")
print("Grafica de posibilidades")
# Graficacion con matplotlib
np.plot(Y)
np.ylabel("Pocas posibilidades")
np.xlabel("Posibilidades")
np.show()